CREATE TABLE usuarios(
    id BIGINT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    senha VARCHAR(100) NOT NULL,
    perfil ENUM("GESTOR", "PROFESSOR", "UNIVERSITARIO") NOT NULL,
    ativo SMALLINT NOT NULL,

    PRIMARY KEY(id)
);