CREATE TABLE materias (
    id BIGINT NOT NULL AUTO_INCREMENT,
    formacao ENUM("ADMINISTRACAO", "BIOMEDICINA", "CIENCIA_COMPUTACAO", "DIREITO", "DESIGN", "ESTETICA", "PSICOLOGIA") NOT NULL,
    nome VARCHAR(50) UNIQUE NOT NULL,
    semestre INTEGER NOT NULL,
    codigo VARCHAR(10) UNIQUE NOT NULL,
    horas_semestre INTEGER NOT NULL,

    PRIMARY KEY(id)
);